//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHBSS.SSIQuery {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://entrance.platform.gov.cn/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://entrance.platform.gov.cn/", ConfigurationName="SSIQuery.CommonInterface")]
    public interface CommonInterface {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:FuncInterface", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SHBSS.SSIQuery.Exception), Action="urn:FuncInterface", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SHBSS.SSIQuery.funcInterfaceResponse funcInterface(SHBSS.SSIQuery.funcInterface request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FuncInterface", ReplyAction="*")]
        System.Threading.Tasks.Task<SHBSS.SSIQuery.funcInterfaceResponse> funcInterfaceAsync(SHBSS.SSIQuery.funcInterface request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="funcInterface", WrapperNamespace="http://entrance.platform.gov.cn/", IsWrapped=true)]
    public partial class funcInterface {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://entrance.platform.gov.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public funcInterface() {
        }
        
        public funcInterface(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="funcInterfaceResponse", WrapperNamespace="http://entrance.platform.gov.cn/", IsWrapped=true)]
    public partial class funcInterfaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://entrance.platform.gov.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public funcInterfaceResponse() {
        }
        
        public funcInterfaceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommonInterfaceChannel : SHBSS.SSIQuery.CommonInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonInterfaceClient : System.ServiceModel.ClientBase<SHBSS.SSIQuery.CommonInterface>, SHBSS.SSIQuery.CommonInterface {
        
        public CommonInterfaceClient() {
        }
        
        public CommonInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SHBSS.SSIQuery.funcInterfaceResponse SHBSS.SSIQuery.CommonInterface.funcInterface(SHBSS.SSIQuery.funcInterface request) {
            return base.Channel.funcInterface(request);
        }
        
        public string funcInterface(string arg0) {
            SHBSS.SSIQuery.funcInterface inValue = new SHBSS.SSIQuery.funcInterface();
            inValue.arg0 = arg0;
            SHBSS.SSIQuery.funcInterfaceResponse retVal = ((SHBSS.SSIQuery.CommonInterface)(this)).funcInterface(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SHBSS.SSIQuery.funcInterfaceResponse> SHBSS.SSIQuery.CommonInterface.funcInterfaceAsync(SHBSS.SSIQuery.funcInterface request) {
            return base.Channel.funcInterfaceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SHBSS.SSIQuery.funcInterfaceResponse> funcInterfaceAsync(string arg0) {
            SHBSS.SSIQuery.funcInterface inValue = new SHBSS.SSIQuery.funcInterface();
            inValue.arg0 = arg0;
            return ((SHBSS.SSIQuery.CommonInterface)(this)).funcInterfaceAsync(inValue);
        }
    }
}
